# Generated by Django 5.2.6 on 2025-09-10 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('capacidad_total', models.PositiveIntegerField(help_text='Capacidad total en litros')),
                ('litros_actuales', models.PositiveIntegerField(help_text='Litros disponibles actualmente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio_litro_clp', models.DecimalField(decimal_places=2, help_text='Precio por litro en Pesos Chilenos', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros_vendidos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total_clp', models.DecimalField(decimal_places=2, help_text='Cálculo automático: litros * precio_cliente', max_digits=10)),
                ('foto_evidencia', models.ImageField(blank=True, help_text='Foto del surtidor o guía de despacho', null=True, upload_to='evidencias/')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(help_text='Camión desde el que se vendió', on_delete=django.db.models.deletion.PROTECT, to='nembus_app.camion')),
                ('cliente', models.ForeignKey(help_text='Cliente al que se le vendió', on_delete=django.db.models.deletion.PROTECT, to='nembus_app.cliente')),
                ('trabajador', models.ForeignKey(help_text='Usuario que realiza el reporte', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
