# Generated by Django 5.2.6 on 2025-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0002_perfiltrabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltrabajador',
            name='camiones_asignados',
            field=models.ManyToManyField(blank=True, help_text='Camiones que este trabajador puede usar.', to='nembus_app.camion'),
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='clientes_asignados',
            field=models.ManyToManyField(blank=True, help_text='Clientes que este trabajador puede ver.', to='nembus_app.cliente'),
        ),
    ]
