# Generated by Django 5.2.6 on 2025-09-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0003_perfiltrabajador_camiones_asignados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='costo_flete_clp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de flete fijo en Pesos Chilenos', max_digits=10),
        ),
    ]
