# Generated by Django 5.2.6 on 2025-09-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0004_cliente_costo_flete_clp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteventa',
            name='costo_flete_clp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo del flete al momento de la venta', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteventa',
            name='monto_combustible_clp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cálculo: litros * precio_cliente', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='monto_total_clp',
            field=models.DecimalField(decimal_places=2, help_text='Suma de combustible + flete', max_digits=10),
        ),
    ]
