# Generated by Django 5.2.6 on 2025-09-27 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0005_reporteventa_costo_flete_clp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltrabajador',
            name='puede_hacer_traspasos',
            field=models.BooleanField(default=False, help_text='Permite registrar traspasos.'),
        ),
        migrations.AlterField(
            model_name='perfiltrabajador',
            name='puede_recargar_combustible',
            field=models.BooleanField(default=False, help_text='Permite registrar recargas.'),
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('camion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entrantes', to='nembus_app.camion')),
                ('camion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salientes', to='nembus_app.camion')),
                ('trabajador', models.ForeignKey(help_text='Trabajador que realiza el traspaso', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
