# Generated by Django 5.2.6 on 2025-09-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0006_perfiltrabajador_puede_hacer_traspasos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltrabajador',
            name='camiones_traspaso',
            field=models.ManyToManyField(blank=True, help_text='Camiones entre los que este trabajador puede hacer traspasos.', related_name='operadores_traspaso', to='nembus_app.camion'),
        ),
    ]
