# Generated by Django 5.2.6 on 2025-09-28 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0007_perfiltrabajador_camiones_traspaso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='camion',
            name='capacidad_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='camion',
            name='litros_actuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='costo_flete_clp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='precio_litro_clp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfiltrabajador',
            name='camiones_asignados',
            field=models.ManyToManyField(blank=True, related_name='operadores_generales', to='nembus_app.camion'),
        ),
        migrations.AlterField(
            model_name='perfiltrabajador',
            name='camiones_traspaso',
            field=models.ManyToManyField(blank=True, related_name='operadores_traspaso', to='nembus_app.camion'),
        ),
        migrations.AlterField(
            model_name='perfiltrabajador',
            name='clientes_asignados',
            field=models.ManyToManyField(blank=True, to='nembus_app.cliente'),
        ),
        migrations.AlterField(
            model_name='perfiltrabajador',
            name='puede_hacer_traspasos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfiltrabajador',
            name='puede_recargar_combustible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nembus_app.camion'),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nembus_app.cliente'),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='costo_flete_clp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='monto_combustible_clp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='monto_total_clp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traspaso',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_litro_clp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litros_actuales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('punto_de_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombas', to='nembus_app.puntodeventa')),
            ],
        ),
        migrations.AddField(
            model_name='perfiltrabajador',
            name='punto_de_venta_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nembus_app.puntodeventa'),
        ),
        migrations.CreateModel(
            name='ReporteTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contador_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('litros_vendidos', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nembus_app.bomba')),
                ('reporte_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='nembus_app.reporteturno')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('punto_de_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='nembus_app.puntodeventa')),
            ],
        ),
        migrations.AddField(
            model_name='reporteturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nembus_app.turno'),
        ),
    ]
