# Generated by Django 5.2.6 on 2025-09-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0008_puntodeventa_alter_camion_capacidad_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomba',
            name='litros_actuales',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lecturabomba',
            name='contador_final',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lecturabomba',
            name='contador_inicial',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lecturabomba',
            name='litros_vendidos',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='costo_flete_clp',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='litros_vendidos',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='monto_combustible_clp',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='monto_total_clp',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
