# Generated by Django 5.2.7 on 2025-10-26 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembus_app', '0009_alter_bomba_litros_actuales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturabomba',
            name='litros_vendidos',
        ),
        migrations.RemoveField(
            model_name='reporteturno',
            name='fecha',
        ),
        migrations.AddField(
            model_name='lecturabomba',
            name='litros_vendidos_turno',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='reporteturno',
            name='esta_abierto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporteturno',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteturno',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lecturabomba',
            name='contador_final',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='RegistroVentaIndividualBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_maquina', models.CharField(max_length=50)),
                ('socio_propietario', models.CharField(max_length=100)),
                ('litros_vendidos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_litro_venta', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('ingreso_registro', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('lectura_bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_individuales', to='nembus_app.lecturabomba')),
            ],
        ),
    ]
